/zhome/06/a/147115/.lsbatch/1648663123.13275111.shell: line 1: !/bin/sh: No such file or directory
Traceback (most recent call last):
  File "/zhome/06/a/147115/BSc_venv/BachelorProject_XAI/torchAttackAttempts/torchAttack#3_ResNet18_CIFAR100.py", line 28, in <module>
    get_ipython().run_line_magic('matplotlib', 'inline')
NameError: name 'get_ipython' is not defined
